### ISSUE TITLE
상태 확인 변수 추가 의견

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#1]
현재 봇의 매매상태가 매수상태인지, 매수대기 상태인지를 확인하는 변수가 있으면 좋겠습니다.
현재 BUY 얼러트가 2번 이상 중복될 때마다 매수가 들어가게 됩니다.

만일 변수가 추가되면, 해당 변수 값이 매수상태인지를 확인하여 중복 얼러트를 RETURN 시키면 될 거 같습니다.

**Comment by MuYoul** [comment]
얼럿이 발생한 대상 거래소의 대상 코인에 대해 매매가 진행 중일 때 진행중인 것과 동일한 얼럿이 발생할 경우 이를 무시하는 기능을 넣도록 하겠습니다.

**Comment by MuYoul** [comment]
017fad6
작업 완료

**Comment by MuYoul** [comment]
확인 후 이슈 close부탁드려요 :)

**Comment by letsplayants** [comment]
![image](https://user-images.githubusercontent.com/46505990/51431063-2cc79f80-1c67-11e9-8b13-5f215d917b31.png)


업데이트 후, BUY 매매후 거래가 더이상 이루어지지 않습니다.

증세1,  BUY 이후 SELL 매매가 되지 않음.
증세2, 메일 읽기 되지 않음.

**Comment by letsplayants** [comment]
한가지 더 예외 상황이 있는 거 같습니다.

매수 후 프로그램이 종료되었을 경우에, 재실행시 매도가 가능한 상태로 유지되어 결국 매수 2회가 발생될 것 같습니다.
프로그램 초기에 개인 오더 주문을 확인하여 매수상태 여부를 파악하는 것은 어떨까요?

**Comment by letsplayants** [comment]
> ![image](https://user-images.githubusercontent.com/46505990/51431063-2cc79f80-1c67-11e9-8b13-5f215d917b31.png)
> 
> 업데이트 후, BUY 매매후 거래가 더이상 이루어지지 않습니다.
> 
> 증세1, BUY 이후 SELL 매매가 되지 않음.
> 증세2, 메일 읽기 되지 않음.

다시 재실행하니 이후부터는 잘 되고 있습니다.

**Comment by MuYoul** [comment]
> 한가지 더 예외 상황이 있는 거 같습니다.
> 
> 매수 후 프로그램이 종료되었을 경우에, 재실행시 매도가 가능한 상태로 유지되어 결국 매수 2회가 발생될 것 같습니다.
> 프로그램 초기에 개인 오더 주문을 확인하여 매수상태 여부를 파악하는 것은 어떨까요?

오더를 넣으면 오더ID라는 것이 나옵니다. 오더 ID가 있는 오더에 대해서는 프로그램에서 제어(조회, 취소)가 가능합니다. 오더 ID가 없는 경우 현재 어떤 주문이 들어있는지 조회가 안됩니다. 즉 거래소 웹에서 주문을 넣은 후 프로그램에서 이를 알 방법이 없습니다.

그리고 다음과 같은 상황에서 문제가 발생할 것 같습니다.
1. 어떠한 이유로 프로그램이 종료됨
2. 알람이 지속적으로 발생함
3. 프로그램이 종료되었다는 사실을 인지
4. 프로그램 재구동

이 때 3,4번의 상황에서 2번이 얼마나 일어났는지 알 수 없습니다. 그래서 알려주신 의견대로 수행을 하게 되면 원치않은 결과를 얻을 수 있습니다. 그래서 프로그램이 재실행되면 마지막 액션을 기억하지 않습니다. 그냥 처음부터 READY상태에서 시작합니다. 그래서 최초의 시그널에 따라 BUY, SELL을 수행할 수 있습니다.

**Comment by letsplayants** [comment]
이슈 주제였던 중복 시그널에대한 처리는 잘 되고 있습니다.
초기 상태에 대한 제 의견이 지금보다 더 좋을 수 있다는 보장이 없군요.
이 이슈는 종료하도록 하겠습니다. ^^
