### ISSUE TITLE
텔레그램 연동 건

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#11]
텔레그램으로 연동하여 매수, 매매 결과 값을 메시징할 수 있다면 좋겠습니다.
이 기능은 제가 추가하도록 하겠습니다.

**Comment by letsplayants** [comment]
기능 추가하였는데, 텔레그램을 연동하고 싶지 않을 때에 대비하여 예외처리는 하지 못했습니다.

**Comment by MuYoul** [comment]
설정값으로 동작하게 만들어두겠습니다

**Comment by MuYoul** [comment]
https://github.com/letsplayants/Ants-Auto-Trading-Bot/commit/a43589a36e656aedde8e2cfd3db302ec875f30d9

처리완료

**Comment by MuYoul** [comment]
구조 개편 후 텔레그램 기능이 빠져 있었음.

재작업 수행함

**Comment by MuYoul** [comment]
cc968da9c3ee02cd5ce3581915d89eda20212779

거래소 매매 후 텔레그램으로 출력함
