### ISSUE TITLE
로그 파일에 빈값 출력

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#13]
매매일지 로그에 빈값이 출력됩니다.

start KRW : 10,058	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 128	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 128	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 19,983	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW
start KRW : 9,629	usage KRW : 10,000
Action	units	price	total	fee	Accumulate KRW

**Comment by MuYoul** [comment]
해당로그는 프로그램이 시작할때 찍히는 로그입니다.
프로그램이 재시작할때마다 찍히는 로그인데 매매가 없이 프로그램이 연속적으로 재시작하면 이런 로그가 발생할 수 있습니다.

프로그램 시작이라고 명시적인 로그를 한줄 넣겠습니다

Ps. 로그앞에 시간을 찍은 것 같은데 시간이 안나오네요? 로그 앞에 시간도 추가하겠습니다.

**Comment by letsplayants** [comment]
매매가 한 사이클 이루어진 상태에서도 로그가 안찍히는 것 같습니다.

**Comment by MuYoul** [comment]
시작하실때 로그를 삭제하시고 트레이딩 로그와 함께 맵핑해서 확인 할 수 있을까요?
Buy중 워닝이 뜨는 것(#12 )과 함께 묶여서 발생하는 이슈 같습니다.

**Comment by MuYoul** [comment]
5437729
이슈 해결.

merage 할 때 실수로 변수를 올바르게 지정하지 않았었음. 그래서 발생한 문제
