### ISSUE TITLE
텔레그램 사용 유무 기능 오류건

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#15]
텔레그램 사용유무 기능을 오늘 추가해주셨는데,
use 옵션을 사용하지 않아도,
bot을 초기화 하는 과정에서 telegram 정보가 없는 유저는 에러가 발생합니다.

telegram token 값이 없어도 에러가 없으면 좋겠습니다.

**Comment by MuYoul** [comment]
수정했습니다 :)

**Comment by MuYoul** [comment]
수정한 내용에 버그가 있어서 추가로 수정했습니다

https://github.com/letsplayants/Ants-Auto-Trading-Bot/commit/e11a5dd9aaf612f6a6a33dcf483f8d36c7ba3823

**Comment by letsplayants** [comment]
지금 다운받았습니다.
테스트 후 잘되면 이슈 닫겠습니다. ^^
