### ISSUE TITLE
알람을 더 빠르게 받기 위해서 TradingView를 사용하여 알람 서비스 사이트 제작

### ISSUE THREAD

**Issue by MuYoul** [letsplayants/Ants-Auto-Trading-Bot#18]
트레이딩 뷰의 차트를 공개 사이트에 사용하면 무료료 사용할 수 있다고 나와 있습니다.

이에 트레이딩뷰 차트를 사용하여 사이트를 구축한 후 특정 지표를 추가합니다.
그리고 특정 지표의 알람이 뜨는 것을 아마도 서버에서 캐치를 할 수 있을 것입니다.
이 알람을 캐치하여 서비스에 등록된 모든 유저들에게 시그널을 전달합니다.

봇은 수신된 시그널을 사용하여 더 빠르게 트레이딩을 수행하게 될 것입니다.

이를 위해서 확인할 사항이 있는데 다음과 같습니다.
  - 트레이딩뷰의 공개 차트에 유료지표를 사용 가능한지?
  - 알람 설정이 가능하고 알람 설정을 할 경우 서버 감지가 가능한지?

위의 두 가지가 검증이 되면 시그널 서비스 + 자동 매매 봇의 조합이 완성될 것입니다.

**Comment by letsplayants** [comment]
제가 알기로는 무료 공개 형태의 차트에서는 유료 지표나 커스텀 지표가 사용이 되지 않습니다.
예전에 한번 시도해봤는데 레퍼런스 지표만 나오더군요. ㅠ
