### ISSUE TITLE
이메일 얼럿이 올 때 마켓 규칙변경이 필요

### ISSUE THREAD

**Issue by MuYoul** [letsplayants/Ants-Auto-Trading-Bot#19]
지금은 BTC를 기준으로 되어있는데, 코인이름과 마켓이름이 3글자가 아닌 경우가 있음. 이를 위해서 구분자를 사용하여 나눠야함
ex) ARDR/BTC, BTC/USDT, POWR/KRW, IQ/KRW

**Comment by letsplayants** [comment]
저도 이 문제로 따로 처리한게 있었는데 말씀하신 것처럼 해도 좋을 거 같습니다.
종합해보면,

#BTC/KRW #1M #SELL #BITHUMB

이렇게 얼러트를 넣으면 되겠군요.

**Comment by MuYoul** [comment]
5127a8b8033507a3c905f4a7db43a82d995b8244

적용완료
