### ISSUE TITLE
봇 실행 시점을 저장하는 시간 변수 추가 건

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#2]
봇이 실행되기전 메일에 얼럿트이 쌓인 경우, 봇이 실행되면서 해당 얼럿트 매매를 수행할 수 있는 리스크가 있습니다.

봇 실행시점을 저장하는 시간변수를 추가하여, 실행 이전의 얼러트는 무시할 수 있는 기능이 있으면 좋겠습니다.

**Comment by MuYoul** [comment]
c009a42
구현 완료

**Comment by letsplayants** [comment]
메일 폴더의 모든 메일을 '읽음'상태로 변경하는 것이 가장 효율적인 방법이 맞는 거 같습니다. 
이미 읽혀진 메일이 가치가 없다면, 읽음 or 삭제로 폴더를 초기화 하는 것은 어떨까요?
메일 용량 문제도 있고, 문제가 없다면 삭제도 괜찮은 거 같습니다.

**Comment by MuYoul** [comment]
> 메일 폴더의 모든 메일을 '읽음'상태로 변경하는 것이 가장 효율적인 방법이 맞는 거 같습니다.
> 이미 읽혀진 메일이 가치가 없다면, 읽음 or 삭제로 폴더를 초기화 하는 것은 어떨까요?
> 메일 용량 문제도 있고, 문제가 없다면 삭제도 괜찮은 거 같습니다.

네. 처음에 삭제를 할까 했었는데, 이 부분도 옵션으로 빼도 될 것 같습니다.
거래 내역이랑 알람 발생이랑 매칭을 시켜보려고 일부러 삭제를 하지않고 '읽음'으로 처리해뒀습니다.

추후 사용자가 삭제를 원할 때 삭제할 수 있도록 옵션으로 추가를 하도록 하겠습니다

**Comment by letsplayants** [comment]
넵 유연하게 옵션으로 처리하면 되겠네요. ^^
