### ISSUE TITLE
다양한 거래소 지원

### ISSUE THREAD

**Issue by MuYoul** [letsplayants/Ants-Auto-Trading-Bot#4]
binance, bitfinex와 같은 대형 거래소도 지원할 수 있으면 좋겠습니다

**Comment by letsplayants** [comment]
바이낸스와 빗파 관련해서 모듈 찾아보겠습니다. ^^

**Comment by MuYoul** [comment]
관련 모듈을 찾아주시면 작업하는데 큰 도움이 될 것 같습니다

빗썸도 모듈을 이용했었는데 원하는 기능이 없고 소소한 수정꺼리가 생겨서 그냥 코드 자체를 포함시켜버렸습니다

아마도 다른 거래소들도 관련 모듈을 찾아서 사용하면서 팔요하면 코드를 포한하고 개조할 것 같습니다

**Comment by MuYoul** [comment]
149dc33e993b3dfcd5afe60466d63d4ebbde0fa2

빗썸, 업빗, 바낸 지원으로 다양한 거래소 지원 구조 검증 완료

앞으로는 지원되는 거래소를 늘이면서 기능 점검 및 버그 수정하면 될 것 같습니다
