### ISSUE TITLE
중요 데이터 보안

### ISSUE THREAD

**Issue by MuYoul** [letsplayants/Ants-Auto-Trading-Bot#5]
API key, email등과 같은 주요 정보가 config에 포함됩니다.

이 정보들을 쉽게 볼 수 없도록 암호화 하거나 정책 또는 다양한 기법으로 보안을 하고 싶은데 좋은 방법이 없을까요?

**Comment by letsplayants** [comment]
파이썬에서 쉽게 지원하는 sqlite는 디비 암호화가 강하지 않은거죠?
저도 방법을 찾아보겠습니다. ^^

**Comment by MuYoul** [comment]
네 디비안에 들어간다고해도 평문그대로 저장이 되니깐요. 스키마 구조는 오픈 프로젝트라서 쉽게 파악할 수 있습니다.

사용자가 암호를 넣어서 중요 데이터와 같은 것들을 복호화해서 사용하도록 하면 좋겠네요.

Rsa같은 키를 지정해서 설정파일을 만들고 복호화도 이를 통해서 하도록하면 되겠네요.

기본은 시스템에 있는 rsa키를 찾아보고 없을 경우 선택할 수 있도록하고 암호화 자체를 옵션으로 선택할 수 있도록 해야겠네요.

rsa방식으로 진행하도록 하겠습니다

**Comment by MuYoul** [comment]
82eeea6abfc997346165acf3f30ffca9f8fff7f9

RSA를 사용하여 문자열 암호화 및 복호화 테스트 코드 확보

앞으로 작업 목록
- [ ] 거래소 key파일 암호화시켜 하나의 파일로 취합
- [ ] 등록된 key 검증 기능
- [ ] shell 프로그램 제작

해당 기능을 가진 shell을 만들어서 key가 노출되지 않도록 하면 될 것 같습니다.

**Comment by MuYoul** [comment]
e1fd1d3e6417730cc3ea128173db7bd4f726a147
shell 완성
key 추가 기능, 연결 검사 기능 포함

**Comment by MuYoul** [comment]
7f6e4c093975c4751e1eaafee67cd9ad2f8727a1
exchange api key 암호화 완료.
설정에서 암호화된 키를 읽는 방식으로 강제됨
