### ISSUE TITLE
다종목 거래를 위한 제안

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#6]
비트코인에 국한되어 있는 고정된 거래 종목을, 다종목으로 늘리고 원하는 만큼 거래할 수 있도록 하는 방법을 제안드립니다.

프로그램에서 종목을 지정하는 것이 아니라, 얼러트 메일에서 받은 #으로 파싱되는 1번 항목을 바로 거래 할 수 있도록 처리하면 좋을 거 같습니다.

어떻게 생각하시나요?

**Comment by letsplayants** [comment]
매매조건이 어느정도 있는 건 알고 있었는데, 코인마다 있는 건 몰랐었네요.
이건 말씀하신대로 포괄적으로 점검하고 진행하는게 좋겠군요. ^^

**Comment by MuYoul** [comment]
49a99b18804d52b731e6e163b44e3608f25df31d
부분 진행중

**Comment by MuYoul** [comment]
5127a8b8033507a3c905f4a7db43a82d995b8244

다양한 코인/마켓 및 거래소 지원 기초 구조 완료
