### ISSUE TITLE
매매일지 기능을 위한 디비 적용

### ISSUE THREAD

**Issue by letsplayants** [letsplayants/Ants-Auto-Trading-Bot#7]
해당 봇으로 이루어진 매매에 대한 일지 기능을 건의 드립니다.
파일로그 방식보다는 디비 방식으로 처리하고, 각종 통계 기능을 이후에 적용하면 좋겠습니다.

**Comment by MuYoul** [comment]
일단 trading.log에 매매일지를 기록해뒀습니다. 구분자는 \t를 사용해서 엑셀로 긁어가셔서 사용하셔도 될것입니다.

로그가 정리가 좀 안되었는데, 디비로 갈 것 생각해서 딱히 더 정리하지는 않았습니다

**Comment by letsplayants** [comment]
네 일단 엑셀로 정리하도록 하겠습니다. ^^

**Comment by MuYoul** [comment]
이 작업은 매매일지 기록가 디비 적용으로 나눠서 작업하겠습니다.

디비적용껀은 새로운 이슈로 등록해서 작업 목록에 올리겠습니다

**Comment by MuYoul** [comment]
https://www.sqlalchemy.org/ 를 사용하여 ORM을 지원하려고 합니다.

NoSQL의 경우는 당장은 필요없겠지만 부분적으로 필요하게 될 경우 Model을 그대로 넣을 수 있도록 적절히 추상화 하여 지원하면 될 것입니다.

1차 목표는 SQLite3를 사용하여 거래기록을 남기는 것입니다.

**Comment by MuYoul** [comment]
Csv출력용 툴 만들어야함

Csvout.py trading --filename data.db --output report20190220234433.csv 포멧으로 생성
